name: Android CI

on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repo
      uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create keystore.properties
      run: |
        echo "storeFile=app/keystore.jks" > keystore.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
        
    - name: Decode and save keystore file
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > app/keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Gradle Clean
      run: ./gradlew clean

    - name: Gradle Lint
      run: ./gradlew lint
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Code coverage test
      run: ./gradlew jacocoTest
