name: Lint and Build Debug

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint-build-debug:
    name: Run Lint and Build Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant Gradle wrapper permission
        run: chmod +x ./gradlew

      - name: Create dummy keystore.properties to prevent build failure
        run: |
          echo "storeFile=\"dummy.jks\"" > keystore.properties
          echo "keyAlias=dummy" >> keystore.properties
          echo "keyPassword=dummy" >> keystore.properties
          echo "storePassword=dummy" >> keystore.properties

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Assemble debug build
        run: ./gradlew assembleDebug

      - name: Upload Lint Report (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html
