name: Lint and Build Debug

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint-build-debug:
    name: Run Lint and Build Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant Gradle wrapper permission
        run: chmod +x ./gradlew

      - name: Create dummy keystore.properties to prevent build failure
        run: |
          echo "storeFile=\"dummy.jks\"" > keystore.properties
          echo "keyAlias=dummy" >> keystore.properties
          echo "keyPassword=dummy" >> keystore.properties
          echo "storePassword=dummy" >> keystore.properties

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Assemble debug build
        run: ./gradlew assembleDebug

      - name: Upload Lint Report (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

      - name: Get version name from Gradle
        id: version
        run: |
          VERSION_NAME=$(./gradlew -q :app:printVersionName)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Get project name
        id: project_name
        run: |
          PROJECT_NAME=$(grep 'rootProject.name' settings.gradle.kts | cut -d '=' -f2 | tr -d '" ')
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          
      - name: Rename APK
        run: |
         mkdir -p output_apk
         cp app/build/outputs/apk/debug/app-debug.apk output_apk/${PROJECT_NAME}-v${VERSION_NAME}-debug.apk

      - name: Send APK to Telegram
        run: |
         curl -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
             -F document=@output_apk/${{ env.PROJECT_NAME }}-v${{ env.VERSION_NAME }}-debug.apk \
             -F caption="📦 *${{ env.PROJECT_NAME }}*\n🛠 Build: `debug`\n🔖 Version: `${{ env.VERSION_NAME }}`" \
             -F parse_mode=Markdown \
             https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument
